spring.application.name=MS_ABC_SERVICE_BITACORA_USUARIO
spring.datasource.url=${ORACLE_HOST}
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=180000
spring.datasource.hikari.max-lifetime=300000


